sudo: false
language: python
os:
  - linux
  # - osx
env:
  - PYTHON_VERSION="3.4"
  - PYTHON_VERSION="3.5"
  - PYTHON_VERSION="3.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels https://conda.anaconda.org/biocore
  - conda update -q conda
  - conda info -a
  ## Install PHYML
  # - wget http://www.atgc-montpellier.fr/download/binaries/phyml/PhyML-3.1.zip
  # - unzip PhyML-3.1.zip
  # - mv ./PhyML-3.1/PhyML-3.1_linux64 ./PhyML-3.1/phyml
  # - export PATH=$PWD/PhyML-3.1/phyml:$PATH
  ## Install RANGER
  # - wget http://compbio.mit.edu/ranger-dtl/ranger-dtl-linux.tar.gz
  # - tar zxvf ranger-dtl-linux.tar.gz
  # - export PATH=$PWD/ranger-dtl-linux:$PATH
  ## Install Java goodies
  # - mkdir java-files
  ## Install PhyloNet
  # - wget http://bioinfo.cs.rice.edu/sites/g/files/bxs266/f/kcfinder/files/PhyloNet_3.5.7.jar -O java-files/PhyloNet_3.5.7.jar --no-check-certificate
install:
  # Install Python packages and some external programs using conda + pip
  - conda create -n test_env python=$PYTHON_VERSION --file ci/conda_requirements.txt
  - source activate test_env
  - conda install -c bioconda diamond
  - pip install -r ci/pip_requirements.txt
  - pip install .
  # Install OrthoFinder (requires Python 2)
  - conda create -n horizomer_py2 -c bioconda python=2 orthofinder
script:
  - WITH_COVERAGE=TRUE make all
  # - nosetests --with-doctest --with-coverage
  # - flake8 .
after_success:
  - coveralls
